# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f7d9e59b2778fe7c05750bacdac7c396f01c86080690cd8dcc04ecc7a9ce546e4d49713e2edbb37f9c8e4915523456059a783c7e938f7d6ac1e58021aa2550f

test:
  secret_key_base: b7c8d0beee34db8f8918c30d3752f0e5e4d1e788e1f1b5f684a48fb4867a0cbdfa79a03149a635cd4e79f648c0e020a5f6061b886b32bc41afcf12272d60f08e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
